CREATE TABLE IF NOT EXISTS public.user_tbl
(
    fld_userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fld_username character(15) COLLATE pg_catalog."default" NOT NULL,
    fld_password text COLLATE pg_catalog."default" NOT NULL,
    fld_email character(30) COLLATE pg_catalog."default" NOT NULL,
    fld_type character(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_tbl_pkey PRIMARY KEY (fld_userid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_tbl
    OWNER to postgres;



CREATE TABLE IF NOT EXISTS public.mainnav_tbl
(
    fld_subid integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 10 CACHE 1 ),
    fld_subcode character(64) COLLATE pg_catalog."default" NOT NULL,
    fld_subname character(64) COLLATE pg_catalog."default" NOT NULL,
    fld_subicon character(32) COLLATE pg_catalog."default",
    CONSTRAINT mainnav_tbl_pkey PRIMARY KEY (fld_subid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.mainnav_tbl
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.nav_tbl
(
    fld_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100 CACHE 1 ),
    fld_pcode character(16) COLLATE pg_catalog."default" NOT NULL,
    fld_pname character(64) COLLATE pg_catalog."default" NOT NULL,
    fld_subcode character(16) COLLATE pg_catalog."default",
    fld_order integer NOT NULL DEFAULT 1,
    fld_visit boolean NOT NULL DEFAULT true,
    fld_page character(64) COLLATE pg_catalog."default",
    fld_icon character(24) COLLATE pg_catalog."default",
    fld_type integer NOT NULL DEFAULT 1,
    CONSTRAINT nav_tbl_pkey PRIMARY KEY (fld_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.nav_tbl
    OWNER to postgres;

    CREATE TABLE IF NOT EXISTS public.req_tbl
(
    fld_reqid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fld_company character(128) COLLATE pg_catalog."default" NOT NULL,
    fld_customer character(128) COLLATE pg_catalog."default",
    fld_phone character(64) COLLATE pg_catalog."default" NOT NULL,
    fld_email character(64) COLLATE pg_catalog."default",
    fld_address character(128) COLLATE pg_catalog."default",
    CONSTRAINT req_tbl_pkey PRIMARY KEY (fld_reqid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.req_tbl
    OWNER to postgres;