CREATE TABLE IF NOT EXISTS public.user_tbl
(
    fld_userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fld_username character(15) COLLATE pg_catalog."default" NOT NULL,
    fld_password text COLLATE pg_catalog."default" NOT NULL,
    fld_email character(30) COLLATE pg_catalog."default" NOT NULL,
    fld_type character(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_tbl_pkey PRIMARY KEY (fld_userid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_tbl
    OWNER to postgres;